language: c

services:
  - docker

script:
  - docker run archlinux:latest bash ./.ci/test.sh

env:
  - CONFIG=mnist WITH_PROGRESS_EMBEDDING=0
  - CONFIG=mnist WITH_PROGRESS_EMBEDDING=1
  - CONFIG=cifar10 WITH_PROGRESS_EMBEDDING=0
  - CONFIG=cifar10 WITH_PROGRESS_EMBEDDING=1

jobs:
  include:
    script: docker run centos:7 bash ./.ci/test-centos7.sh
