language: c

services:
  - docker

script:
  - docker run -v "$PWD:/stateful-cnn" archlinux:latest bash -c "cd /stateful-cnn && ./.ci/test.sh"

env:
  - CONFIG=mnist WITH_PROGRESS_EMBEDDING=0
  - CONFIG=mnist WITH_PROGRESS_EMBEDDING=1
  - CONFIG=cifar10 WITH_PROGRESS_EMBEDDING=0
  - CONFIG=cifar10 WITH_PROGRESS_EMBEDDING=1

jobs:
  include:
    script: docker run -v "$PWD:/stateful-cnn" centos:7 bash -c "cd /stateful-cnn && ./.ci/test-centos7.sh"
