name: Testing

on: push

jobs:
  mnist_baseline:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CONFIG: mnist
      WITH_PROGRESS_EMBEDDING: 0
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./.ci/test.sh

  mnist_stateful:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CONFIG: mnist
      WITH_PROGRESS_EMBEDDING: 1
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./.ci/test.sh

  cifar10_baseline:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CONFIG: cifar10
      WITH_PROGRESS_EMBEDDING: 0
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./.ci/test.sh

  cifar10_stateful:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CONFIG: cifar10
      WITH_PROGRESS_EMBEDDING: 1
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./.ci/test.sh

  mnist_baseline_cmsis:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CONFIG: mnist
      WITH_PROGRESS_EMBEDDING: 0
      USE_ARM_CMSIS: 1
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout ARM-CMSIS
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/ARM-CMSIS_5
        ref: patched
        path: ARM-CMSIS_5
    - name: Test
      run: ./.ci/test.sh

  mnist_stateful_cmsis:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CONFIG: mnist
      WITH_PROGRESS_EMBEDDING: 1
      USE_ARM_CMSIS: 1
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout ARM-CMSIS
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/ARM-CMSIS_5
        ref: patched
        path: ARM-CMSIS_5
    - name: Test
      run: ./.ci/test.sh

  cifar10_baseline_cmsis:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CONFIG: cifar10
      WITH_PROGRESS_EMBEDDING: 0
      USE_ARM_CMSIS: 1
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout ARM-CMSIS
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/ARM-CMSIS_5
        ref: patched
        path: ARM-CMSIS_5
    - name: Test
      run: ./.ci/test.sh

  cifar10_stateful_cmsis:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CONFIG: cifar10
      WITH_PROGRESS_EMBEDDING: 1
      USE_ARM_CMSIS: 1
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout ARM-CMSIS
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/ARM-CMSIS_5
        ref: patched
        path: ARM-CMSIS_5
    - name: Test
      run: ./.ci/test.sh

  debug_build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CONFIG: mnist
      DEBUG_BUILD: 1
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./.ci/test.sh

  old_system:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./.ci/test-centos7.sh
