name: Testing

on: push

_arch_config: &arch_config
  runs-on: ubuntu-latest
  container: archlinux:latest
  steps:
  - uses: actions/checkout@v2
  - name: Test
    run: ./.ci/test.sh

jobs:
  mnist_baseline:
    <<: *arch_config
    env:
      CONFIG: mnist
      WITH_PROGRESS_EMBEDDING: 0

  mnist_stateful:
    <<: *arch_config
    env:
      CONFIG: mnist
      WITH_PROGRESS_EMBEDDING: 1

  cifar10_baseline:
    <<: *arch_config
    env:
      CONFIG: cifar10
      WITH_PROGRESS_EMBEDDING: 0

  cifar10_stateful:
    <<: *arch_config
    env:
      CONFIG: cifar10
      WITH_PROGRESS_EMBEDDING: 1

  debug_build:
    <<: *arch_config
    env:
      DEBUG_BUILD: 1

  old_system:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: ./.ci/test-centos7.sh
