name: Testing

on: push

jobs:
  mnist_baseline:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: ./.ci/test.sh
    env:
      CONFIG: mnist
      WITH_PROGRESS_EMBEDDING: 0

  mnist_stateful:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CONFIG: mnist
      WITH_PROGRESS_EMBEDDING: 1
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: ./.ci/test.sh

  cifar10_baseline:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CONFIG: cifar10
      WITH_PROGRESS_EMBEDDING: 0
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: ./.ci/test.sh

  cifar10_stateful:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CONFIG: cifar10
      WITH_PROGRESS_EMBEDDING: 1
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: ./.ci/test.sh

  debug_build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      DEBUG_BUILD: 1
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: ./.ci/test.sh

  old_system:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: ./.ci/test-centos7.sh
