# GitHub actions should really support YAML anchors
# https://github.community/t/support-for-yaml-anchors/16128

name: Testing

on: push

jobs:
  mnist_baseline:
    runs-on: ubuntu-20.04
    container: archlinux:latest
    env:
      CONFIG: '--all-samples --baseline mnist'
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./utils/test.sh

  mnist_stateful:
    runs-on: ubuntu-20.04
    container: archlinux:latest
    env:
      CONFIG: '--all-samples --stateful mnist'
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./utils/test.sh

  mnist_japari_b1:
    runs-on: ubuntu-20.04
    container: archlinux:latest
    env:
      CONFIG: '--japari --batch-size 1 mnist'
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./utils/test.sh

  mnist_japari_b2:
    runs-on: ubuntu-20.04
    container: archlinux:latest
    env:
      CONFIG: '--japari --batch-size 2 mnist'
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./utils/test.sh

  mnist_japari_b4:
    if: false
    runs-on: ubuntu-20.04
    container: archlinux:latest
    env:
      CONFIG: '--japari --batch-size 4 mnist'
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./utils/test.sh

  cifar10_baseline:
    runs-on: ubuntu-20.04
    container: archlinux:latest
    env:
      CONFIG: '--all-samples --baseline cifar10'
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./utils/test.sh

  cifar10_stateful:
    runs-on: ubuntu-20.04
    container: archlinux:latest
    env:
      CONFIG: '--all-samples --stateful cifar10'
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./utils/test.sh

  cifar10_japari_b4:
    runs-on: ubuntu-20.04
    container: archlinux:latest
    env:
      CONFIG: '--japari --batch-size 4 cifar10'
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./utils/test.sh

  kws_baseline:
    runs-on: ubuntu-20.04
    container: archlinux:latest
    env:
      CONFIG: '--all-samples --baseline kws'
    steps:
    - name: Install git
      run: 'pacman -Syu --noconfirm && pacman -S --noconfirm git'
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./utils/test.sh

  kws_japari_b2:
    runs-on: ubuntu-20.04
    container: archlinux:latest
    env:
      CONFIG: '--japari --batch-size 2 kws'
    steps:
    - name: Install git
      run: 'pacman -Syu --noconfirm && pacman -S --noconfirm git'
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./utils/test.sh

  kws_stateful:
    runs-on: ubuntu-20.04
    container: archlinux:latest
    env:
      CONFIG: '--all-samples --stateful kws'
    steps:
    - name: Install git
      run: 'pacman -Syu --noconfirm && pacman -S --noconfirm git'
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./utils/test.sh

  mnist_stateful_cmsis:
    runs-on: ubuntu-20.04
    container: archlinux:latest
    env:
      CONFIG: '--stateful mnist'
      USE_ARM_CMSIS: 1
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout ARM-CMSIS
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/ARM-CMSIS_5
        ref: patched
        path: ARM-CMSIS_5
    - name: Test
      run: ./utils/test.sh

  debug_build:
    runs-on: ubuntu-20.04
    container: archlinux:latest
    env:
      CONFIG: '--stateful mnist'
      DEBUG_BUILD: 1
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./utils/test.sh

  old_system:
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout TI-DSPLib
      uses: actions/checkout@v2
      with:
        repository: EMCLab-Sinica/DSPLib
        path: TI-DSPLib
        token: ${{ secrets.access_token }}
    - name: Test
      run: ./utils/test-centos7.sh
